### ISSUE TITLE
If modeled timestamp is created using MAKE_DATE() dashboard has a 404 error

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1133] opened 2022-10-28 04:25 UTC
**Describe the bug**
When I try to use a model where the timestamp was created using MAKE_DATE() to create a dashboard I get a 404 error

**To Reproduce**
1. pull in a data set that has year, month, day
2. write a model with SELECT MAKE_DATE(year, month, day)
3. click the "create dashboard" button
4. 404 error

**Expected behavior**
I expect this function to generate a timestamp that works with the dashboard.

**Comment by hamilton** [comment] 2022-10-28 04:40
this may actually be a duplicate of https://github.com/rilldata/rill-developer/issues/1065

**Comment by hamilton** [comment] 2022-10-28 13:10
@magorlick what does the terminal say when this appears?

**Comment by hamilton** [comment] 2022-10-31 16:01
We'll need a similar piece of code for checking quotes as we had for the character length fix. Assigning @AdityaHegde to this.

**Comment by AdityaHegde** [comment] 2022-11-01 06:01
The issue happens when dimension column name has quotes as well. Here is a query to reproduce issue in both measure and dimension,
```
select make_date(2022, month, "day"), replace(domain, '.com', '') from (
  select
    date_part('day', timestamp) as day,
    date_part('month', timestamp) as month, domain
  from AdBids group by day, month, domain
)
```

**Closed** 2022-11-02 08:00 UTC
Labels: bug
