### ISSUE TITLE
Autogenerate the label and description for the autogenerated `count(*)` measure

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#724] opened 2022-08-03 16:59 UTC
It'd be great to showcase how the `label` and `description` fields are supposed to be used by generating them for the autogenerated `count(*)` measures.

E.g. label = "Count", description = "Number of observations"

**Comment by hamilton** [comment] 2022-08-03 19:09
duplicate of https://github.com/rilldata/rill-developer/issues/554

**Closed by hamilton** 2022-08-03 19:09 UTC
Labels: duplicate, nit
